In [1]:
import pandas as pd

data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005,
                1006, 1007, 1008, 1009, 1010],

    "Date": ["2025-01-05", "2025-01-06", "2025-01-07",
             "2025-01-10", "2025-01-12", "2025-01-15",
             "2025-01-18", "2025-01-20", "2025-01-22",
             "2025-01-25"],

    "Customer": ["C101", "C102", "C101", "C103", "C104",
                 "C102", "C105", "C103", "C106", "C101"],

    "Product": ["Laptop", "Mouse", "Keyboard", "Chair", "Desk",
                "Monitor", "Headphones", "Chair", "Keyboard", "Mouse"],

    "Category": ["Electronics", "Electronics", "Electronics",
                 "Furniture", "Furniture", "Electronics",
                 "Electronics", "Furniture", "Electronics",
                 "Electronics"],

    "Quantity": [1, 2, 1, 2, 1, 1, 3, 1, 2, 3],

    "Price": [55000, 800, 1500, 4500, 7000,
              15000, 2000, 4500, 1500, 800],

    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Delhi",
             "Mumbai", "Bangalore", "Pune", "Chennai", "Delhi"]
}

df = pd.DataFrame(data)

In [2]:
df

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
0,1001,2025-01-05,C101,Laptop,Electronics,1,55000,Delhi
1,1002,2025-01-06,C102,Mouse,Electronics,2,800,Mumbai
2,1003,2025-01-07,C101,Keyboard,Electronics,1,1500,Delhi
3,1004,2025-01-10,C103,Chair,Furniture,2,4500,Pune
4,1005,2025-01-12,C104,Desk,Furniture,1,7000,Delhi
5,1006,2025-01-15,C102,Monitor,Electronics,1,15000,Mumbai
6,1007,2025-01-18,C105,Headphones,Electronics,3,2000,Bangalore
7,1008,2025-01-20,C103,Chair,Furniture,1,4500,Pune
8,1009,2025-01-22,C106,Keyboard,Electronics,2,1500,Chennai
9,1010,2025-01-25,C101,Mouse,Electronics,3,800,Delhi

In [4]:
df.shape

(10, 8)

In [5]:
df.size

80

In [7]:
df.columns

Index(['OrderID', 'Date', 'Customer', 'Product', 'Category', 'Quantity',
       'Price', 'City'],
      dtype='str')

In [14]:
for i in df.columns:
    print(i,' : ',type(i))

OrderID  :  <class 'str'>
Date  :  <class 'str'>
Customer  :  <class 'str'>
Product  :  <class 'str'>
Category  :  <class 'str'>
Quantity  :  <class 'str'>
Price  :  <class 'str'>
City  :  <class 'str'>

In [15]:
df.dtypes

OrderID     int64
Date          str
Customer      str
Product       str
Category      str
Quantity    int64
Price       int64
City          str
dtype: object

In [12]:
df.head()

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
0,1001,2025-01-05,C101,Laptop,Electronics,1,55000,Delhi
1,1002,2025-01-06,C102,Mouse,Electronics,2,800,Mumbai
2,1003,2025-01-07,C101,Keyboard,Electronics,1,1500,Delhi
3,1004,2025-01-10,C103,Chair,Furniture,2,4500,Pune
4,1005,2025-01-12,C104,Desk,Furniture,1,7000,Delhi

In [13]:
df.tail()

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
5,1006,2025-01-15,C102,Monitor,Electronics,1,15000,Mumbai
6,1007,2025-01-18,C105,Headphones,Electronics,3,2000,Bangalore
7,1008,2025-01-20,C103,Chair,Furniture,1,4500,Pune
8,1009,2025-01-22,C106,Keyboard,Electronics,2,1500,Chennai
9,1010,2025-01-25,C101,Mouse,Electronics,3,800,Delhi

In [20]:
df['OrderID'].nunique()

10

In [18]:
df['Product'].nunique()

7

In [19]:
df['Product'].unique()

<ArrowStringArray>
['Laptop', 'Mouse', 'Keyboard', 'Chair', 'Desk', 'Monitor', 'Headphones']
Length: 7, dtype: str

In [22]:
df['Category'].value_counts()

Category
Electronics    7
Furniture      3
Name: count, dtype: int64

In [23]:
df['Category'].unique()

<ArrowStringArray>
['Electronics', 'Furniture']
Length: 2, dtype: str

In [25]:
print(df['Quantity'].sum())

17

In [32]:
df['Customer']

0    C101
1    C102
2    C101
3    C103
4    C104
5    C102
6    C105
7    C103
8    C106
9    C101
Name: Customer, dtype: str

In [99]:
df[['Customer']]

  Customer
0     C101
1     C102
2     C101
3     C103
4     C104
5     C102
6     C105
7     C103
8     C106
9     C101

In [45]:
df['Price'].max()

55000

In [47]:
df.loc[df['Price'] == df['Price'].max()]

   OrderID        Date Customer Product     Category  Quantity  Price   City
0     1001  2025-01-05     C101  Laptop  Electronics         1  55000  Delhi

In [50]:
df['Price'].mean()

np.float64(9260.0)

In [51]:
df_priced = df.loc[df['Price']>=df['Price'].mean()]

In [52]:
df_priced

   OrderID        Date Customer  Product     Category  Quantity  Price    City
0     1001  2025-01-05     C101   Laptop  Electronics         1  55000   Delhi
5     1006  2025-01-15     C102  Monitor  Electronics         1  15000  Mumbai

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   10 non-null     int64
 1   Date      10 non-null     str
 2   Customer  10 non-null     str
 3   Product   10 non-null     str
 4   Category  10 non-null     str
 5   Quantity  10 non-null     int64
 6   Price     10 non-null     int64
 7   City      10 non-null     str
dtypes: int64(3), str(5)
memory usage: 1.1 KB

In [57]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
OrderID,10.0,1005.5,3.027650,1001.0,1003.25,1005.5,1007.75,1010.0
Quantity,10.0,1.7,0.823273,1.0,1.00,1.5,2.00,3.0
Price,10.0,9260.0,16639.324238,800.0,1500.00,3250.0,6375.00,55000.0

In [58]:
df[['OrderID', 'Product', 'Quantity', 'Price']]

   OrderID     Product  Quantity  Price
0     1001      Laptop         1  55000
1     1002       Mouse         2    800
2     1003    Keyboard         1   1500
3     1004       Chair         2   4500
4     1005        Desk         1   7000
5     1006     Monitor         1  15000
6     1007  Headphones         3   2000
7     1008       Chair         1   4500
8     1009    Keyboard         2   1500
9     1010       Mouse         3    800

In [59]:
df[df['Price']>5000]

   OrderID        Date Customer  Product     Category  Quantity  Price    City
0     1001  2025-01-05     C101   Laptop  Electronics         1  55000   Delhi
4     1005  2025-01-12     C104     Desk    Furniture         1   7000   Delhi
5     1006  2025-01-15     C102  Monitor  Electronics         1  15000  Mumbai

In [62]:
df[df['Quantity']>1]

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
1,1002,2025-01-06,C102,Mouse,Electronics,2,800,Mumbai
3,1004,2025-01-10,C103,Chair,Furniture,2,4500,Pune
6,1007,2025-01-18,C105,Headphones,Electronics,3,2000,Bangalore
8,1009,2025-01-22,C106,Keyboard,Electronics,2,1500,Chennai
9,1010,2025-01-25,C101,Mouse,Electronics,3,800,Delhi

In [63]:
df[df['City']=='Delhi']

   OrderID        Date Customer   Product     Category  Quantity  Price   City
0     1001  2025-01-05     C101    Laptop  Electronics         1  55000  Delhi
2     1003  2025-01-07     C101  Keyboard  Electronics         1   1500  Delhi
4     1005  2025-01-12     C104      Desk    Furniture         1   7000  Delhi
9     1010  2025-01-25     C101     Mouse  Electronics         3    800  Delhi

In [71]:
df.loc[df['Price']>1000,['Product','Price','City']]

      Product  Price       City
0      Laptop  55000      Delhi
2    Keyboard   1500      Delhi
3       Chair   4500       Pune
4        Desk   7000      Delhi
5     Monitor  15000     Mumbai
6  Headphones   2000  Bangalore
7       Chair   4500       Pune
8    Keyboard   1500    Chennai

In [74]:
df.loc[df['Price']>1000][['Product','Price','City']]

      Product  Price       City
0      Laptop  55000      Delhi
2    Keyboard   1500      Delhi
3       Chair   4500       Pune
4        Desk   7000      Delhi
5     Monitor  15000     Mumbai
6  Headphones   2000  Bangalore
7       Chair   4500       Pune
8    Keyboard   1500    Chennai

In [79]:
df[(df['Category']=='Electronics') & (df['Price']>1000)]

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
0,1001,2025-01-05,C101,Laptop,Electronics,1,55000,Delhi
2,1003,2025-01-07,C101,Keyboard,Electronics,1,1500,Delhi
5,1006,2025-01-15,C102,Monitor,Electronics,1,15000,Mumbai
6,1007,2025-01-18,C105,Headphones,Electronics,3,2000,Bangalore
8,1009,2025-01-22,C106,Keyboard,Electronics,2,1500,Chennai

In [80]:
df[(df['City']=='Delhi')& (df['Quantity']>1)]

   OrderID        Date Customer Product     Category  Quantity  Price   City
9     1010  2025-01-25     C101   Mouse  Electronics         3    800  Delhi

In [82]:
df[(df['City']=='Delhi') | (df['City']=='Mumbai')]

,OrderID,Date,Customer,Product,Category,Quantity,Price,City
0,1001,2025-01-05,C101,Laptop,Electronics,1,55000,Delhi
1,1002,2025-01-06,C102,Mouse,Electronics,2,800,Mumbai
2,1003,2025-01-07,C101,Keyboard,Electronics,1,1500,Delhi
4,1005,2025-01-12,C104,Desk,Furniture,1,7000,Delhi
5,1006,2025-01-15,C102,Monitor,Electronics,1,15000,Mumbai
9,1010,2025-01-25,C101,Mouse,Electronics,3,800,Delhi

In [95]:
df[df['City'].isin(['Delhi','Mumbai','Pune'])][df.columns.drop('Date')]

   OrderID Customer   Product     Category  Quantity  Price    City
0     1001     C101    Laptop  Electronics         1  55000   Delhi
1     1002     C102     Mouse  Electronics         2    800  Mumbai
2     1003     C101  Keyboard  Electronics         1   1500   Delhi
3     1004     C103     Chair    Furniture         2   4500    Pune
4     1005     C104      Desk    Furniture         1   7000   Delhi
5     1006     C102   Monitor  Electronics         1  15000  Mumbai
7     1008     C103     Chair    Furniture         1   4500    Pune
9     1010     C101     Mouse  Electronics         3    800   Delhi

In [97]:
df.drop('Date',axis=1)[df['City'].isin(['Delhi','Mumbai','Pune'])]

   OrderID Customer   Product     Category  Quantity  Price    City
0     1001     C101    Laptop  Electronics         1  55000   Delhi
1     1002     C102     Mouse  Electronics         2    800  Mumbai
2     1003     C101  Keyboard  Electronics         1   1500   Delhi
3     1004     C103     Chair    Furniture         2   4500    Pune
4     1005     C104      Desk    Furniture         1   7000   Delhi
5     1006     C102   Monitor  Electronics         1  15000  Mumbai
7     1008     C103     Chair    Furniture         1   4500    Pune
9     1010     C101     Mouse  Electronics         3    800   Delhi